# Generated by Django 5.1.3 on 2024-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transport_hotelbooking_tour_booking_transportbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
